apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsphere-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-mongodb
  template:
    metadata:
      labels:
        app: shopsphere-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017